using SharpGPX;
using SharpGPX.GPX1_1;
using System;
using System.Collections.Generic;
using System.Text;

namespace GarminRun
{
    static class ExportGPX
    {
        public static GpxClass CreateGpx() => new()
        {
            Metadata = new metadataType()
            {
                author = new personType("Alexander von Lünen", "knobs1723@gmail.com"),
                link = new linkTypeCollection([new linkType("https://github.com/avlunen/garmin_running", "AvL")]),
                name = "Track",
                desc = "Track generated by GarminRun",
                copyright = new copyrightType("AvL", "2026"),
            },
        };

        public static void Export(string fn, string vname, string vcomment, string vdesc, MyLine line)
        {
            // create a new file
            GpxClass newGpx = CreateTrack(vname, vcomment, vdesc, line);

            // test settings XmlWriterSettings
            GpxClass.XmlWriterSettings.Encoding = Encoding.UTF8;

            newGpx.ToFile(fn);

            _ = newGpx.ToXml();
        }

        public static GpxClass CreateTrack(string vname, string vcomment, string vdesc, MyLine line)
        {
            if (vname == null || line == null) return null;

            GpxClass track = CreateGpx();

            trkType mtrack = new()
            {
                name = vname,
                cmt = vcomment ?? "",
                desc = vdesc ?? ""
            };

            trksegTypeCollection trksegs = [];

            foreach (MyLineSegment s in line.GetSegs())
            {
                trksegType trkseg = new();
                trkseg.AddPoint(new wptType(s.m_start.Y, s.m_start.X, s.m_fields.Malt, s.m_fields.Mtimestamp));
                trkseg.AddPoint(new wptType(s.m_end.Y, s.m_end.X, s.m_fields.Malt, s.m_fields.Mtimestamp));

                trksegs.Add(trkseg);
            }

            mtrack.trkseg = trksegs;
            track.AddTrack(mtrack);
            track.Metadata.bounds = track.GetBounds();
            return track;
        }

    }
}